### ISSUE TITLE
FoodOrdering Backend

### ISSUE THREAD

**Issue by VonLisboa** [yangxch/FoodOrdering#1]
Have backend of this app on github?

**Comment by yangxch** [comment]
no, but I can share it with you.
link: https://pan.baidu.com/s/1c6uaZs_DGk3BEbmzeEwJmg
password: v5jy

At 2018-09-02 04:30:55, "Glaucio" <notifications@github.com> wrote:


Have backend of this app on github?

**Comment by helsinq** [comment]
very cool, thank you!
